[build]
  command = "pnpm install && pnpm --filter frontend build"
  publish = "apps/frontend/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Puedes agregar variables de entorno aqu√≠
#[[headers]]
#  for = "/api/*"
#  [headers.values]
#    Access-Control-Allow-Origin = "*"
