[build]
  command = "pnpm --filter frontend build"
  publish = "apps/frontend/dist"

# Puedes agregar variables de entorno aqu√≠
#[[headers]]
#  for = "/api/*"
#  [headers.values]
#    Access-Control-Allow-Origin = "*"
